### ISSUE TITLE
Finishing Touches

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#58]
**TODO**
- [x] Setup SkyBlock information area
- [x] Setup SkyWars information area
- [x] Setup server store
- [x] Set UltimateSurvival prices

**Information areas**
I'd like it to be more interactive than just signs. We either need to go for a GUI plugin, or make the MobPortals send them information somehow. We could do messages (easier/quicker to implement) or a popup information menu (much more interactive). The popup would take a little bit longer.
