### ISSUE TITLE
Enable Beta Mode

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#65]
**TODO**
- [x] Enable UltimateSurvival world access (normal, nether, end)
- [x] Enable BSkyblock world access (normal, nether, end)
- [x] Enable `/sw join`
- [x] Setup MobPortals to new areas
- [x] Install new Autorank "paths" file
- [x] Install and configure RewardPro with "dailyReward" and "referral"
- [x] Update server motd
